
name: Checkmarx AST Scan
 
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
         repository: DanEllisHub/sec-test-2
      - name: Checkmarx AST Github Action
        uses: Checkmarx/ast-github-action@2.0.23
        with:
          base_uri: https://ast.checkmarx.net
    # Provide the Tenant for AST portal URL
          cx_tenant: cx_ast_cec_na_test_nellis_david
    # Client ID for AST portal authentication
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
    # Secret key for AST portal authentication
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
